services:
  - type: web
    name: ps-prototype-server
    runtime: python
    rootDir: server
    buildCommand: pip install -r requirements.txt && chmod +x scripts/start.sh
    startCommand: ./scripts/start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
